_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: b6c1fbb4-9ce0-4553-af56-a5db28e12089
name: 'The Eclectic Meme Conspiracy'
mail: info@eclecticmeme.com
slogan: ''
page:
  403: ''
  404: ''
  front: /node/2
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: ''
